Vagrant.configure("2") do |config|
  config.vm.define "helk" do |cfg|
    cfg.vm.box = "generic/debian11"
    cfg.vm.hostname = "helk"
    cfg.vm.provision "shell", path: "fix_nameserver.sh"
    cfg.vm.provision "shell", inline: "apt-get -qq update"
    cfg.vm.provision "shell", path: "install_docker.sh"
    cfg.vm.provision "shell", path: "install_docker_compose.sh"
    cfg.vm.provision "shell", path: "install_aptlab-helk.sh", args: ["192.168.57.105"]
    cfg.vm.network "private_network", ip: "192.168.57.105", gateway: "192.168.57.1", dns: "8.8.8.8"

    cfg.vm.provider "libvirt" do |lv, override|
      lv.default_prefix = "APT-Lab_"
      lv.graphics_type = "vnc"
      lv.video_type = "vga"
      lv.input :type => "tablet", :bus => "usb"
      lv.video_vram = 32768
      lv.memory = 20480
      lv.cpus = 6
      # This is required for Vagrant to properly configure the network interfaces.
      # See https://github.com/clong/DetectionLab/wiki/LibVirt-Support for more information
      lv.management_network_name = "VagrantMgmt"
      lv.management_network_address = "192.168.123.0/24"
      lv.management_network_mode = "none"
      lv.cpu_mode = "host-passthrough"
      # Which storage pool path to use. Default to /var/lib/libvirt/images or ~/.local/share/libvirt/images depending on if you are running a system or user QEMU/KVM session.
      #libvirt.storage_pool_path = '/media/storage_nvme/system_session_vm_pool'
      lv.storage_pool_name = 'default'
      override.vm.synced_folder './', '/vagrant', disabled: true 
    end
  end

  config.vm.define "win10" do |cfg|
    cfg.vm.box = "windows_10_libvirt"
    cfg.vm.hostname = "win10"
    cfg.vm.boot_timeout = 1200
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 1200
    cfg.winrm.retry_limit = 20
    cfg.vm.network "private_network", ip: "192.168.57.104", gateway: "192.168.57.1", dns: "8.8.8.8"

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip 192.168.57.104 -dns 8.8.8.8 -gateway 192.168.57.1" 
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-redteam.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-choco-extras.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-winlogbeat.ps1", privileged: false
    cfg.vm.provision "shell", inline: "Write-Host 'Win10 Provisioning Complete!'", privileged: false

    cfg.vm.provider "libvirt" do |lv, override|
      lv.default_prefix = "APT-Lab_"
      lv.graphics_type = "spice"
      lv.video_type = "qxl"
      lv.input :type => "tablet", :bus => "usb"
      lv.video_vram = 32768
      lv.memory = 4096
      lv.cpus = 4
      override.vm.synced_folder '.', '/', type: 'winrm' 
    end
  end

  config.vm.define "kali" do |cfg|
    cfg.vm.box = "elrey741/kali-linux_amd64"
    cfg.vm.hostname = "kali"
    cfg.vm.provision "shell", path: "fix_nameserver.sh"
    cfg.vm.provision "shell", inline: "apt-get -qq update"
    cfg.vm.provision "shell", path: "install_docker.sh"
    cfg.vm.provision "shell", path: "install_docker_compose.sh"
    cfg.vm.provision "shell", path: "install_mitre_caldera.sh"
    cfg.vm.network "private_network", ip: "192.168.57.234", gateway: "192.168.57.1", dns: "8.8.8.8"

    cfg.vm.provider "libvirt" do |lv, override|
      lv.default_prefix = "APT-Lab_"
      lv.graphics_type = "vnc"
      lv.video_type = "vga"
      lv.input :type => "tablet", :bus => "usb"
      lv.video_vram = 32768
      lv.memory = 8192
      lv.cpus = 4
      lv.management_network_name = "VagrantMgmt"
      lv.management_network_address = "192.168.123.0/24"
      lv.management_network_mode = "none"
      lv.cpu_mode = "host-passthrough"
      lv.storage_pool_name = 'default'
      override.vm.synced_folder './', '/vagrant', disabled: true
    end
  end

  config.vm.define "vpn" do |cfg|
    cfg.vm.box = "generic/debian11"
    cfg.vm.hostname = "vpn"
    cfg.vm.provision "shell", path: "fix_nameserver.sh"
    cfg.vm.provision "shell", path: "fix_eth2_to_public_ip.sh", args: ["192.168.1.1", "255.255.255.0"]
    cfg.vm.provision "shell", inline: "apt-get -qq update"
    cfg.vm.provision "shell", path: "install_docker.sh"
    cfg.vm.provision "shell", path: "install_docker_compose.sh"
    cfg.vm.provision "shell", path: "install_wireguard.sh", args: ["192.168.1.1", 51820, 6, "192.168.57.0/24"]
    cfg.vm.provision "shell", path: "set_iptables_to_deny_eth2.sh"
    cfg.vm.provision "shell", inline: "PASSWORD=$(echo $RANDOM | sha256sum | head -c 12) && echo \"vagrant:$PASSWORD\" | chpasswd "
    cfg.vm.network "private_network", ip: "192.168.57.235", gateway: "192.168.57.1", dns: "8.8.8.8"
    # vagrant-libvirt only support TCP protocol for forwarded ports
    # See https://github.com/vagrant-libvirt/vagrant-libvirt#forwarded-ports= for more information
    # cfg.vm.network "forwarded_port", guest: 51820, host: 51820, host_ip: "0.0.0.0", protocol: "udp"
    cfg.vm.network "public_network", dev: "eno1"

    cfg.vm.provider "libvirt" do |lv, override|
      lv.default_prefix = "APT-Lab_"
      lv.graphics_type = "vnc"
      lv.video_type = "vga"
      lv.input :type => "tablet", :bus => "usb"
      lv.video_vram = 32768
      lv.memory = 8192
      lv.cpus = 2
      lv.management_network_name = "VagrantMgmt"
      lv.management_network_address = "192.168.123.0/24"
      lv.management_network_mode = "none"
      lv.cpu_mode = "host-passthrough"
      lv.storage_pool_name = 'default'
      override.vm.synced_folder './', '/vagrant', disabled: true
    end
  end
end
